### ISSUE TITLE
Move server project to poetry

### ISSUE THREAD

**Issue by jamshale** [decentralized-identity/didwebvh-server-py#33]
Should move the server project to poetry. Makes configuration, publishing and dependency management much better.

**Comment by PatStLouis** [comment]
Great idea!

**Comment by PatStLouis** [comment]
@jamshale Your PR has been merged, I will let you close this issue if you feel its complete!

**Comment by PatStLouis** [comment]
@jamshale actually I will close it now, feel free to re-open it if more work is required. #34 has been merged to address this
