### ISSUE TITLE
Demo - Submit Initial Log Entry

### ISSUE THREAD

**Issue by jamshale** [decentralized-identity/didwebvh-server-py#64]
I'm following through the postman demo and everything is working well until the `Submit Initial Log Entry` step. I'm getting a `{"detail":"Key unauthorized."}` response.

Not sure if I'm doing something wrong or not. Seems like the demo docs might be a bit out of date.

**Comment by PatStLouis** [comment]
Thanks for raising this, I will have a look at the current state of the postman collections
