### ISSUE TITLE
Rename project to didwebvh-server-py

### ISSUE THREAD

**Issue by PatStLouis** [decentralized-identity/didwebvh-server-py#77]
@kimdhamilton @swcurran @esune 

Now that the specification name change has been completed, we would like to start migrating this project.

I've opened PR #76 to make the required code changes, if someone (@kimdhamilton 👀) could rename this project to `didwebvh-server-py` we will be able to complete the migration.

**Comment by swcurran** [comment]
The repo has been renamed -- enjoy!
